//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subscription) DeepCopyInto(out *Subscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SubscriptionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(SubscriptionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subscription.
func (in *Subscription) DeepCopy() *Subscription {
	if in == nil {
		return nil
	}
	out := new(Subscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Subscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionList) DeepCopyInto(out *SubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Subscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionList.
func (in *SubscriptionList) DeepCopy() *SubscriptionList {
	if in == nil {
		return nil
	}
	out := new(SubscriptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpec) DeepCopyInto(out *SubscriptionSpec) {
	*out = *in
	if in.Channel != nil {
		in, out := &in.Channel, &out.Channel
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(SubscriptionSpecConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InstallPlanApproval != nil {
		in, out := &in.InstallPlanApproval, &out.InstallPlanApproval
		*out = new(string)
		**out = **in
	}
	if in.StartingCSV != nil {
		in, out := &in.StartingCSV, &out.StartingCSV
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpec.
func (in *SubscriptionSpec) DeepCopy() *SubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfig) DeepCopyInto(out *SubscriptionSpecConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]SubscriptionSpecConfigEnvElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]SubscriptionSpecConfigEnvFromElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(SubscriptionSpecConfigResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(SubscriptionSpecConfigSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]SubscriptionSpecConfigTolerationsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]SubscriptionSpecConfigVolumeMountsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]SubscriptionSpecConfigVolumesElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfig.
func (in *SubscriptionSpecConfig) DeepCopy() *SubscriptionSpecConfig {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvElem) DeepCopyInto(out *SubscriptionSpecConfigEnvElem) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(SubscriptionSpecConfigEnvElemValueFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvElem.
func (in *SubscriptionSpecConfigEnvElem) DeepCopy() *SubscriptionSpecConfigEnvElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvElemValueFrom) DeepCopyInto(out *SubscriptionSpecConfigEnvElemValueFrom) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef)
		(*in).DeepCopyInto(*out)
	}
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(SubscriptionSpecConfigEnvElemValueFromFieldRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceFieldRef != nil {
		in, out := &in.ResourceFieldRef, &out.ResourceFieldRef
		*out = new(SubscriptionSpecConfigEnvElemValueFromResourceFieldRef)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SubscriptionSpecConfigEnvElemValueFromSecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvElemValueFrom.
func (in *SubscriptionSpecConfigEnvElemValueFrom) DeepCopy() *SubscriptionSpecConfigEnvElemValueFrom {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvElemValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef) DeepCopyInto(out *SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef.
func (in *SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef) DeepCopy() *SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvElemValueFromConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvElemValueFromFieldRef) DeepCopyInto(out *SubscriptionSpecConfigEnvElemValueFromFieldRef) {
	*out = *in
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvElemValueFromFieldRef.
func (in *SubscriptionSpecConfigEnvElemValueFromFieldRef) DeepCopy() *SubscriptionSpecConfigEnvElemValueFromFieldRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvElemValueFromFieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvElemValueFromResourceFieldRef) DeepCopyInto(out *SubscriptionSpecConfigEnvElemValueFromResourceFieldRef) {
	*out = *in
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	if in.Divisor != nil {
		in, out := &in.Divisor, &out.Divisor
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvElemValueFromResourceFieldRef.
func (in *SubscriptionSpecConfigEnvElemValueFromResourceFieldRef) DeepCopy() *SubscriptionSpecConfigEnvElemValueFromResourceFieldRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvElemValueFromResourceFieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvElemValueFromSecretKeyRef) DeepCopyInto(out *SubscriptionSpecConfigEnvElemValueFromSecretKeyRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvElemValueFromSecretKeyRef.
func (in *SubscriptionSpecConfigEnvElemValueFromSecretKeyRef) DeepCopy() *SubscriptionSpecConfigEnvElemValueFromSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvElemValueFromSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvFromElem) DeepCopyInto(out *SubscriptionSpecConfigEnvFromElem) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(SubscriptionSpecConfigEnvFromElemConfigMapRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigEnvFromElemSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvFromElem.
func (in *SubscriptionSpecConfigEnvFromElem) DeepCopy() *SubscriptionSpecConfigEnvFromElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvFromElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvFromElemConfigMapRef) DeepCopyInto(out *SubscriptionSpecConfigEnvFromElemConfigMapRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvFromElemConfigMapRef.
func (in *SubscriptionSpecConfigEnvFromElemConfigMapRef) DeepCopy() *SubscriptionSpecConfigEnvFromElemConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvFromElemConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigEnvFromElemSecretRef) DeepCopyInto(out *SubscriptionSpecConfigEnvFromElemSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigEnvFromElemSecretRef.
func (in *SubscriptionSpecConfigEnvFromElemSecretRef) DeepCopy() *SubscriptionSpecConfigEnvFromElemSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigEnvFromElemSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigResources) DeepCopyInto(out *SubscriptionSpecConfigResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigResources.
func (in *SubscriptionSpecConfigResources) DeepCopy() *SubscriptionSpecConfigResources {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigSelector) DeepCopyInto(out *SubscriptionSpecConfigSelector) {
	*out = *in
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]SubscriptionSpecConfigSelectorMatchExpressionsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigSelector.
func (in *SubscriptionSpecConfigSelector) DeepCopy() *SubscriptionSpecConfigSelector {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigSelectorMatchExpressionsElem) DeepCopyInto(out *SubscriptionSpecConfigSelectorMatchExpressionsElem) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigSelectorMatchExpressionsElem.
func (in *SubscriptionSpecConfigSelectorMatchExpressionsElem) DeepCopy() *SubscriptionSpecConfigSelectorMatchExpressionsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigSelectorMatchExpressionsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigTolerationsElem) DeepCopyInto(out *SubscriptionSpecConfigTolerationsElem) {
	*out = *in
	if in.Effect != nil {
		in, out := &in.Effect, &out.Effect
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(int)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigTolerationsElem.
func (in *SubscriptionSpecConfigTolerationsElem) DeepCopy() *SubscriptionSpecConfigTolerationsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigTolerationsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumeMountsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumeMountsElem) {
	*out = *in
	if in.MountPropagation != nil {
		in, out := &in.MountPropagation, &out.MountPropagation
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SubPath != nil {
		in, out := &in.SubPath, &out.SubPath
		*out = new(string)
		**out = **in
	}
	if in.SubPathExpr != nil {
		in, out := &in.SubPathExpr, &out.SubPathExpr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumeMountsElem.
func (in *SubscriptionSpecConfigVolumeMountsElem) DeepCopy() *SubscriptionSpecConfigVolumeMountsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumeMountsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElem) {
	*out = *in
	if in.AwsElasticBlockStore != nil {
		in, out := &in.AwsElasticBlockStore, &out.AwsElasticBlockStore
		*out = new(SubscriptionSpecConfigVolumesElemAwsElasticBlockStore)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureDisk != nil {
		in, out := &in.AzureDisk, &out.AzureDisk
		*out = new(SubscriptionSpecConfigVolumesElemAzureDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureFile != nil {
		in, out := &in.AzureFile, &out.AzureFile
		*out = new(SubscriptionSpecConfigVolumesElemAzureFile)
		(*in).DeepCopyInto(*out)
	}
	if in.Cephfs != nil {
		in, out := &in.Cephfs, &out.Cephfs
		*out = new(SubscriptionSpecConfigVolumesElemCephfs)
		(*in).DeepCopyInto(*out)
	}
	if in.Cinder != nil {
		in, out := &in.Cinder, &out.Cinder
		*out = new(SubscriptionSpecConfigVolumesElemCinder)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(SubscriptionSpecConfigVolumesElemConfigMap)
		(*in).DeepCopyInto(*out)
	}
	if in.Csi != nil {
		in, out := &in.Csi, &out.Csi
		*out = new(SubscriptionSpecConfigVolumesElemCsi)
		(*in).DeepCopyInto(*out)
	}
	if in.DownwardAPI != nil {
		in, out := &in.DownwardAPI, &out.DownwardAPI
		*out = new(SubscriptionSpecConfigVolumesElemDownwardAPI)
		(*in).DeepCopyInto(*out)
	}
	if in.EmptyDir != nil {
		in, out := &in.EmptyDir, &out.EmptyDir
		*out = new(SubscriptionSpecConfigVolumesElemEmptyDir)
		(*in).DeepCopyInto(*out)
	}
	if in.Ephemeral != nil {
		in, out := &in.Ephemeral, &out.Ephemeral
		*out = new(SubscriptionSpecConfigVolumesElemEphemeral)
		(*in).DeepCopyInto(*out)
	}
	if in.Fc != nil {
		in, out := &in.Fc, &out.Fc
		*out = new(SubscriptionSpecConfigVolumesElemFc)
		(*in).DeepCopyInto(*out)
	}
	if in.FlexVolume != nil {
		in, out := &in.FlexVolume, &out.FlexVolume
		*out = new(SubscriptionSpecConfigVolumesElemFlexVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.Flocker != nil {
		in, out := &in.Flocker, &out.Flocker
		*out = new(SubscriptionSpecConfigVolumesElemFlocker)
		(*in).DeepCopyInto(*out)
	}
	if in.GcePersistentDisk != nil {
		in, out := &in.GcePersistentDisk, &out.GcePersistentDisk
		*out = new(SubscriptionSpecConfigVolumesElemGcePersistentDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.GitRepo != nil {
		in, out := &in.GitRepo, &out.GitRepo
		*out = new(SubscriptionSpecConfigVolumesElemGitRepo)
		(*in).DeepCopyInto(*out)
	}
	if in.Glusterfs != nil {
		in, out := &in.Glusterfs, &out.Glusterfs
		*out = new(SubscriptionSpecConfigVolumesElemGlusterfs)
		(*in).DeepCopyInto(*out)
	}
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(SubscriptionSpecConfigVolumesElemHostPath)
		(*in).DeepCopyInto(*out)
	}
	if in.Iscsi != nil {
		in, out := &in.Iscsi, &out.Iscsi
		*out = new(SubscriptionSpecConfigVolumesElemIscsi)
		(*in).DeepCopyInto(*out)
	}
	if in.Nfs != nil {
		in, out := &in.Nfs, &out.Nfs
		*out = new(SubscriptionSpecConfigVolumesElemNfs)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(SubscriptionSpecConfigVolumesElemPersistentVolumeClaim)
		(*in).DeepCopyInto(*out)
	}
	if in.PhotonPersistentDisk != nil {
		in, out := &in.PhotonPersistentDisk, &out.PhotonPersistentDisk
		*out = new(SubscriptionSpecConfigVolumesElemPhotonPersistentDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.PortworxVolume != nil {
		in, out := &in.PortworxVolume, &out.PortworxVolume
		*out = new(SubscriptionSpecConfigVolumesElemPortworxVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.Projected != nil {
		in, out := &in.Projected, &out.Projected
		*out = new(SubscriptionSpecConfigVolumesElemProjected)
		(*in).DeepCopyInto(*out)
	}
	if in.Quobyte != nil {
		in, out := &in.Quobyte, &out.Quobyte
		*out = new(SubscriptionSpecConfigVolumesElemQuobyte)
		(*in).DeepCopyInto(*out)
	}
	if in.Rbd != nil {
		in, out := &in.Rbd, &out.Rbd
		*out = new(SubscriptionSpecConfigVolumesElemRbd)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleIO != nil {
		in, out := &in.ScaleIO, &out.ScaleIO
		*out = new(SubscriptionSpecConfigVolumesElemScaleIO)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SubscriptionSpecConfigVolumesElemSecret)
		(*in).DeepCopyInto(*out)
	}
	if in.Storageos != nil {
		in, out := &in.Storageos, &out.Storageos
		*out = new(SubscriptionSpecConfigVolumesElemStorageos)
		(*in).DeepCopyInto(*out)
	}
	if in.VsphereVolume != nil {
		in, out := &in.VsphereVolume, &out.VsphereVolume
		*out = new(SubscriptionSpecConfigVolumesElemVsphereVolume)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElem.
func (in *SubscriptionSpecConfigVolumesElem) DeepCopy() *SubscriptionSpecConfigVolumesElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemAwsElasticBlockStore) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemAwsElasticBlockStore) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Partition != nil {
		in, out := &in.Partition, &out.Partition
		*out = new(int)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemAwsElasticBlockStore.
func (in *SubscriptionSpecConfigVolumesElemAwsElasticBlockStore) DeepCopy() *SubscriptionSpecConfigVolumesElemAwsElasticBlockStore {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemAwsElasticBlockStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemAzureDisk) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemAzureDisk) {
	*out = *in
	if in.CachingMode != nil {
		in, out := &in.CachingMode, &out.CachingMode
		*out = new(string)
		**out = **in
	}
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemAzureDisk.
func (in *SubscriptionSpecConfigVolumesElemAzureDisk) DeepCopy() *SubscriptionSpecConfigVolumesElemAzureDisk {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemAzureDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemAzureFile) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemAzureFile) {
	*out = *in
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemAzureFile.
func (in *SubscriptionSpecConfigVolumesElemAzureFile) DeepCopy() *SubscriptionSpecConfigVolumesElemAzureFile {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemAzureFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemCephfs) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemCephfs) {
	*out = *in
	if in.Monitors != nil {
		in, out := &in.Monitors, &out.Monitors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SecretFile != nil {
		in, out := &in.SecretFile, &out.SecretFile
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigVolumesElemCephfsSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemCephfs.
func (in *SubscriptionSpecConfigVolumesElemCephfs) DeepCopy() *SubscriptionSpecConfigVolumesElemCephfs {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemCephfs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemCephfsSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemCephfsSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemCephfsSecretRef.
func (in *SubscriptionSpecConfigVolumesElemCephfsSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemCephfsSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemCephfsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemCinder) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemCinder) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigVolumesElemCinderSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemCinder.
func (in *SubscriptionSpecConfigVolumesElemCinder) DeepCopy() *SubscriptionSpecConfigVolumesElemCinder {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemCinder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemCinderSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemCinderSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemCinderSecretRef.
func (in *SubscriptionSpecConfigVolumesElemCinderSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemCinderSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemCinderSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemConfigMap) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemConfigMap) {
	*out = *in
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(int)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionSpecConfigVolumesElemConfigMapItemsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemConfigMap.
func (in *SubscriptionSpecConfigVolumesElemConfigMap) DeepCopy() *SubscriptionSpecConfigVolumesElemConfigMap {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemConfigMapItemsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemConfigMapItemsElem) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemConfigMapItemsElem.
func (in *SubscriptionSpecConfigVolumesElemConfigMapItemsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemConfigMapItemsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemConfigMapItemsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemCsi) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemCsi) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.NodePublishSecretRef != nil {
		in, out := &in.NodePublishSecretRef, &out.NodePublishSecretRef
		*out = new(SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.VolumeAttributes != nil {
		in, out := &in.VolumeAttributes, &out.VolumeAttributes
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemCsi.
func (in *SubscriptionSpecConfigVolumesElemCsi) DeepCopy() *SubscriptionSpecConfigVolumesElemCsi {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemCsi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef.
func (in *SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemCsiNodePublishSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPI) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemDownwardAPI) {
	*out = *in
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(int)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemDownwardAPI.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPI) DeepCopy() *SubscriptionSpecConfigVolumesElemDownwardAPI {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemDownwardAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem) {
	*out = *in
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int)
		**out = **in
	}
	if in.ResourceFieldRef != nil {
		in, out := &in.ResourceFieldRef, &out.ResourceFieldRef
		*out = new(SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemDownwardAPIItemsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef) {
	*out = *in
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef) DeepCopy() *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemFieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef) {
	*out = *in
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	if in.Divisor != nil {
		in, out := &in.Divisor, &out.Divisor
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef.
func (in *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef) DeepCopy() *SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemDownwardAPIItemsElemResourceFieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEmptyDir) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEmptyDir) {
	*out = *in
	if in.Medium != nil {
		in, out := &in.Medium, &out.Medium
		*out = new(string)
		**out = **in
	}
	if in.SizeLimit != nil {
		in, out := &in.SizeLimit, &out.SizeLimit
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEmptyDir.
func (in *SubscriptionSpecConfigVolumesElemEmptyDir) DeepCopy() *SubscriptionSpecConfigVolumesElemEmptyDir {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEmptyDir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeral) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeral) {
	*out = *in
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeral.
func (in *SubscriptionSpecConfigVolumesElemEphemeral) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeral {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpec) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataSource != nil {
		in, out := &in.DataSource, &out.DataSource
		*out = new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource)
		(*in).DeepCopyInto(*out)
	}
	if in.DataSourceRef != nil {
		in, out := &in.DataSourceRef, &out.DataSourceRef
		*out = new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.VolumeMode != nil {
		in, out := &in.VolumeMode, &out.VolumeMode
		*out = new(string)
		**out = **in
	}
	if in.VolumeName != nil {
		in, out := &in.VolumeName, &out.VolumeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpec.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpec) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource) {
	*out = *in
	if in.ApiGroup != nil {
		in, out := &in.ApiGroup, &out.ApiGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef) {
	*out = *in
	if in.ApiGroup != nil {
		in, out := &in.ApiGroup, &out.ApiGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecDataSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector) {
	*out = *in
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem.
func (in *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemEphemeralVolumeClaimTemplateSpecSelectorMatchExpressionsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemFc) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemFc) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Lun != nil {
		in, out := &in.Lun, &out.Lun
		*out = new(int)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.TargetWWNs != nil {
		in, out := &in.TargetWWNs, &out.TargetWWNs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Wwids != nil {
		in, out := &in.Wwids, &out.Wwids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemFc.
func (in *SubscriptionSpecConfigVolumesElemFc) DeepCopy() *SubscriptionSpecConfigVolumesElemFc {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemFc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemFlexVolume) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemFlexVolume) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemFlexVolume.
func (in *SubscriptionSpecConfigVolumesElemFlexVolume) DeepCopy() *SubscriptionSpecConfigVolumesElemFlexVolume {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemFlexVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef.
func (in *SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemFlexVolumeSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemFlocker) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemFlocker) {
	*out = *in
	if in.DatasetName != nil {
		in, out := &in.DatasetName, &out.DatasetName
		*out = new(string)
		**out = **in
	}
	if in.DatasetUUID != nil {
		in, out := &in.DatasetUUID, &out.DatasetUUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemFlocker.
func (in *SubscriptionSpecConfigVolumesElemFlocker) DeepCopy() *SubscriptionSpecConfigVolumesElemFlocker {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemFlocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemGcePersistentDisk) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemGcePersistentDisk) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Partition != nil {
		in, out := &in.Partition, &out.Partition
		*out = new(int)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemGcePersistentDisk.
func (in *SubscriptionSpecConfigVolumesElemGcePersistentDisk) DeepCopy() *SubscriptionSpecConfigVolumesElemGcePersistentDisk {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemGcePersistentDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemGitRepo) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemGitRepo) {
	*out = *in
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemGitRepo.
func (in *SubscriptionSpecConfigVolumesElemGitRepo) DeepCopy() *SubscriptionSpecConfigVolumesElemGitRepo {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemGitRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemGlusterfs) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemGlusterfs) {
	*out = *in
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemGlusterfs.
func (in *SubscriptionSpecConfigVolumesElemGlusterfs) DeepCopy() *SubscriptionSpecConfigVolumesElemGlusterfs {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemGlusterfs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemHostPath) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemHostPath) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemHostPath.
func (in *SubscriptionSpecConfigVolumesElemHostPath) DeepCopy() *SubscriptionSpecConfigVolumesElemHostPath {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemHostPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemIscsi) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemIscsi) {
	*out = *in
	if in.ChapAuthDiscovery != nil {
		in, out := &in.ChapAuthDiscovery, &out.ChapAuthDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.ChapAuthSession != nil {
		in, out := &in.ChapAuthSession, &out.ChapAuthSession
		*out = new(bool)
		**out = **in
	}
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.InitiatorName != nil {
		in, out := &in.InitiatorName, &out.InitiatorName
		*out = new(string)
		**out = **in
	}
	if in.IscsiInterface != nil {
		in, out := &in.IscsiInterface, &out.IscsiInterface
		*out = new(string)
		**out = **in
	}
	if in.Portals != nil {
		in, out := &in.Portals, &out.Portals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigVolumesElemIscsiSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemIscsi.
func (in *SubscriptionSpecConfigVolumesElemIscsi) DeepCopy() *SubscriptionSpecConfigVolumesElemIscsi {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemIscsi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemIscsiSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemIscsiSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemIscsiSecretRef.
func (in *SubscriptionSpecConfigVolumesElemIscsiSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemIscsiSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemIscsiSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemNfs) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemNfs) {
	*out = *in
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemNfs.
func (in *SubscriptionSpecConfigVolumesElemNfs) DeepCopy() *SubscriptionSpecConfigVolumesElemNfs {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemNfs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemPersistentVolumeClaim) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemPersistentVolumeClaim) {
	*out = *in
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemPersistentVolumeClaim.
func (in *SubscriptionSpecConfigVolumesElemPersistentVolumeClaim) DeepCopy() *SubscriptionSpecConfigVolumesElemPersistentVolumeClaim {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemPersistentVolumeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemPhotonPersistentDisk) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemPhotonPersistentDisk) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemPhotonPersistentDisk.
func (in *SubscriptionSpecConfigVolumesElemPhotonPersistentDisk) DeepCopy() *SubscriptionSpecConfigVolumesElemPhotonPersistentDisk {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemPhotonPersistentDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemPortworxVolume) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemPortworxVolume) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemPortworxVolume.
func (in *SubscriptionSpecConfigVolumesElemPortworxVolume) DeepCopy() *SubscriptionSpecConfigVolumesElemPortworxVolume {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemPortworxVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjected) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjected) {
	*out = *in
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(int)
		**out = **in
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]SubscriptionSpecConfigVolumesElemProjectedSourcesElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjected.
func (in *SubscriptionSpecConfigVolumesElemProjected) DeepCopy() *SubscriptionSpecConfigVolumesElemProjected {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjected)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElem) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap)
		(*in).DeepCopyInto(*out)
	}
	if in.DownwardAPI != nil {
		in, out := &in.DownwardAPI, &out.DownwardAPI
		*out = new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountToken != nil {
		in, out := &in.ServiceAccountToken, &out.ServiceAccountToken
		*out = new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElem.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElem) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemConfigMapItemsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem) {
	*out = *in
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int)
		**out = **in
	}
	if in.ResourceFieldRef != nil {
		in, out := &in.ResourceFieldRef, &out.ResourceFieldRef
		*out = new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef) {
	*out = *in
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemFieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef) {
	*out = *in
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	in.Divisor.DeepCopyInto(&out.Divisor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemDownwardAPIItemsElemResourceFieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemSecretItemsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.ExpirationSeconds != nil {
		in, out := &in.ExpirationSeconds, &out.ExpirationSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken.
func (in *SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken) DeepCopy() *SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemProjectedSourcesElemServiceAccountToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemQuobyte) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemQuobyte) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemQuobyte.
func (in *SubscriptionSpecConfigVolumesElemQuobyte) DeepCopy() *SubscriptionSpecConfigVolumesElemQuobyte {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemQuobyte)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemRbd) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemRbd) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Keyring != nil {
		in, out := &in.Keyring, &out.Keyring
		*out = new(string)
		**out = **in
	}
	if in.Monitors != nil {
		in, out := &in.Monitors, &out.Monitors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigVolumesElemRbdSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemRbd.
func (in *SubscriptionSpecConfigVolumesElemRbd) DeepCopy() *SubscriptionSpecConfigVolumesElemRbd {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemRbd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemRbdSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemRbdSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemRbdSecretRef.
func (in *SubscriptionSpecConfigVolumesElemRbdSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemRbdSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemRbdSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemScaleIO) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemScaleIO) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.ProtectionDomain != nil {
		in, out := &in.ProtectionDomain, &out.ProtectionDomain
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	in.SecretRef.DeepCopyInto(&out.SecretRef)
	if in.SslEnabled != nil {
		in, out := &in.SslEnabled, &out.SslEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageMode != nil {
		in, out := &in.StorageMode, &out.StorageMode
		*out = new(string)
		**out = **in
	}
	if in.StoragePool != nil {
		in, out := &in.StoragePool, &out.StoragePool
		*out = new(string)
		**out = **in
	}
	if in.VolumeName != nil {
		in, out := &in.VolumeName, &out.VolumeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemScaleIO.
func (in *SubscriptionSpecConfigVolumesElemScaleIO) DeepCopy() *SubscriptionSpecConfigVolumesElemScaleIO {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemScaleIO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemScaleIOSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemScaleIOSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemScaleIOSecretRef.
func (in *SubscriptionSpecConfigVolumesElemScaleIOSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemScaleIOSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemScaleIOSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemSecret) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemSecret) {
	*out = *in
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(int)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionSpecConfigVolumesElemSecretItemsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemSecret.
func (in *SubscriptionSpecConfigVolumesElemSecret) DeepCopy() *SubscriptionSpecConfigVolumesElemSecret {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemSecretItemsElem) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemSecretItemsElem) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemSecretItemsElem.
func (in *SubscriptionSpecConfigVolumesElemSecretItemsElem) DeepCopy() *SubscriptionSpecConfigVolumesElemSecretItemsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemSecretItemsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemStorageos) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemStorageos) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SubscriptionSpecConfigVolumesElemStorageosSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeName != nil {
		in, out := &in.VolumeName, &out.VolumeName
		*out = new(string)
		**out = **in
	}
	if in.VolumeNamespace != nil {
		in, out := &in.VolumeNamespace, &out.VolumeNamespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemStorageos.
func (in *SubscriptionSpecConfigVolumesElemStorageos) DeepCopy() *SubscriptionSpecConfigVolumesElemStorageos {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemStorageos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemStorageosSecretRef) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemStorageosSecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemStorageosSecretRef.
func (in *SubscriptionSpecConfigVolumesElemStorageosSecretRef) DeepCopy() *SubscriptionSpecConfigVolumesElemStorageosSecretRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemStorageosSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpecConfigVolumesElemVsphereVolume) DeepCopyInto(out *SubscriptionSpecConfigVolumesElemVsphereVolume) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.StoragePolicyID != nil {
		in, out := &in.StoragePolicyID, &out.StoragePolicyID
		*out = new(string)
		**out = **in
	}
	if in.StoragePolicyName != nil {
		in, out := &in.StoragePolicyName, &out.StoragePolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpecConfigVolumesElemVsphereVolume.
func (in *SubscriptionSpecConfigVolumesElemVsphereVolume) DeepCopy() *SubscriptionSpecConfigVolumesElemVsphereVolume {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpecConfigVolumesElemVsphereVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatus) DeepCopyInto(out *SubscriptionStatus) {
	*out = *in
	if in.CatalogHealth != nil {
		in, out := &in.CatalogHealth, &out.CatalogHealth
		*out = make([]SubscriptionStatusCatalogHealthElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]SubscriptionStatusConditionsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentCSV != nil {
		in, out := &in.CurrentCSV, &out.CurrentCSV
		*out = new(string)
		**out = **in
	}
	if in.InstallPlanGeneration != nil {
		in, out := &in.InstallPlanGeneration, &out.InstallPlanGeneration
		*out = new(int)
		**out = **in
	}
	if in.InstallPlanRef != nil {
		in, out := &in.InstallPlanRef, &out.InstallPlanRef
		*out = new(SubscriptionStatusInstallPlanRef)
		(*in).DeepCopyInto(*out)
	}
	if in.InstalledCSV != nil {
		in, out := &in.InstalledCSV, &out.InstalledCSV
		*out = new(string)
		**out = **in
	}
	if in.Installplan != nil {
		in, out := &in.Installplan, &out.Installplan
		*out = new(SubscriptionStatusInstallplan)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatus.
func (in *SubscriptionStatus) DeepCopy() *SubscriptionStatus {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatusCatalogHealthElem) DeepCopyInto(out *SubscriptionStatusCatalogHealthElem) {
	*out = *in
	in.CatalogSourceRef.DeepCopyInto(&out.CatalogSourceRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatusCatalogHealthElem.
func (in *SubscriptionStatusCatalogHealthElem) DeepCopy() *SubscriptionStatusCatalogHealthElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatusCatalogHealthElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatusCatalogHealthElemCatalogSourceRef) DeepCopyInto(out *SubscriptionStatusCatalogHealthElemCatalogSourceRef) {
	*out = *in
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(string)
		**out = **in
	}
	if in.FieldPath != nil {
		in, out := &in.FieldPath, &out.FieldPath
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.ResourceVersion != nil {
		in, out := &in.ResourceVersion, &out.ResourceVersion
		*out = new(string)
		**out = **in
	}
	if in.Uid != nil {
		in, out := &in.Uid, &out.Uid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatusCatalogHealthElemCatalogSourceRef.
func (in *SubscriptionStatusCatalogHealthElemCatalogSourceRef) DeepCopy() *SubscriptionStatusCatalogHealthElemCatalogSourceRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatusCatalogHealthElemCatalogSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatusConditionsElem) DeepCopyInto(out *SubscriptionStatusConditionsElem) {
	*out = *in
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = new(string)
		**out = **in
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatusConditionsElem.
func (in *SubscriptionStatusConditionsElem) DeepCopy() *SubscriptionStatusConditionsElem {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatusConditionsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatusInstallPlanRef) DeepCopyInto(out *SubscriptionStatusInstallPlanRef) {
	*out = *in
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(string)
		**out = **in
	}
	if in.FieldPath != nil {
		in, out := &in.FieldPath, &out.FieldPath
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.ResourceVersion != nil {
		in, out := &in.ResourceVersion, &out.ResourceVersion
		*out = new(string)
		**out = **in
	}
	if in.Uid != nil {
		in, out := &in.Uid, &out.Uid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatusInstallPlanRef.
func (in *SubscriptionStatusInstallPlanRef) DeepCopy() *SubscriptionStatusInstallPlanRef {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatusInstallPlanRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatusInstallplan) DeepCopyInto(out *SubscriptionStatusInstallplan) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatusInstallplan.
func (in *SubscriptionStatusInstallplan) DeepCopy() *SubscriptionStatusInstallplan {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatusInstallplan)
	in.DeepCopyInto(out)
	return out
}
