= Kafka Provider
==============

The *Kafka Provider* is responsible for providing access to one or more Kafka
topics.

== ClowdApp Configuration

To request a Kafka topic, a `ClowdApp` would use the `kafkaTopics` stanza, a
partial example of which is shown below.

[source,yaml]
----
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdApp
metadata:
  name: myapp
spec:
  # Other App Config
  kafkaTopics:
  - replicas: 5
    partitions: 5
    topicName: topicOne
  - replicas: 5
    partitions: 5
    topicName: topicTwo
    config:
      retention.ms: "234234234"
      retention.bytes: "2352352"
----

== ClowdEnv Configuration

The *Kafka Provider* will run in one of the following modes. These are set up
by the ClowdEnvironment. Depending on the environment you are running you may
or may not have access to change this mode. More information on provider
configuration is at the bottom of this page.

=== operator

In operator mode, the *Kafka Provider* will provision KafkaTopic CRs to be
consumed by the Strimzi operator. If multiple apps request the same topic, a
mathematical `max` operation will be performed on any partitions, replicas as
well as numerical configuration field, before applying these to the KafkaTopic
CR. The CR will be placed in the environment specified in the `ClowdEnv`. The
topic name will be modified as described above, to facilitate using the same
Kafka instance for multiple apps in differing environments.

=== app-interface

In app-interface mode, the Clowder operator does not create any resources and
simply passes through the topic names from the `ClowdApp` to the client
config. The topics should be created via the usual app-interface means.

== Generated App Configuration

The Kafka configuration appears in the cdappconfig.json with the following
structure. The name that was requested in the `ClowdApp` will be presented as
the `requestedName` attribute in the topic object. The kafka provider modifies
the name in some modes where a single kafka instance is shared between multiple
environments. This allows the same topic name to be requested by apps
in different environments without them polluting each other. Apps should use
the `name` attribute of a topic when connecting to Kafka.

A helper is available below to facilitate quick access via a map.

== Authentication, SSL, and CA Certificates

If the `securityProtocol` field is populated and its value is "SSL" or
"SASL_SSL", then the client should use SSL to communicate with the broker.

NOTE: The `securityProtocol` field has been deprecated from within the SASL
stanza and in the future will only be available at the top level broker
stanza.

If the `cacert` field is populated, clients should use this as the CA trust
list when connecting to the broker. If it is not populated, then the broker's
certificate is expected to be signed using a well-trusted certificate
authority and clients should use the OS default CA trust list.

=== Example JSON structures

Broker is using SSL, a custom CA cert, and username/password auth:
[source,json]
----
{
  "kafka": {
    "brokers": [
      {
        "authtype": "sasl",
        "cacert": "<CA certs in PEM format>",
        "hostname": "hostname.kafka.com",
        "port": 9096,
        "sasl": {
          "password": "pw",
          "saslMechanism": "SCRAM-SHA-512",
          "securityProtocol": "SASL_SSL",
          "username": "username"
        },
        "securityProtocol": "SASL_SSL"
      }
    ],
    "topics": [
      {
        "requestedName": "originalName",
        "name": "actualTopicName",
      }
    ]
  }
}
----

Broker is unsecured (common in ephemeral environments)
[source,json]
----
  "kafka": {
    "brokers": [
      {
        "hostname": "hostname.kafka.com",
        "port": 9092
      }
    ],
    "topics": [
      {
        "requestedName": "originalName",
        "name": "actualTopicName",
      }
    ]
  }
}
----

Broker is using SSL but not SASL, and is signed by a commonly trusted CA (cacert not provided by Clowder)
[source,json]
----
  "kafka": {
    "brokers": [
      {
        "hostname": "hostname.kafka.com",
        "port": 9093,
        "securityProtocol": "SSL"
      }
    ],
    "topics": [
      {
        "requestedName": "originalName",
        "name": "actualTopicName",
      }
    ]
  }
}
----

=== Client access

For supported languages, the kafka configuration is accessed via the following
attribute names.

[options="header"]
|=================================
| Language  | Attribute Name      
| Python    | `LoadedConfig.kafka`
| Go        | `LoadedConfig.Kafka`
| Javscript | `LoadedConfig.kafka`
| Ruby      | `LoadedConfig.kafka`
|=================================

=== Client helpers

`KafkaTopics` Returns a map of topic objects, using the original requested name
as the key and the topic object the value. `KafkaServers` Returns a list of
Kafka broker strings comprising of hostname and port.

////
[options="header"]
|================================================================
| Name        | Kafka Topics                      | Kafka Servers
| Description | Returns a map of topic objects, using the original requested name as the key and the topic object the value. | Returns a list of Kafka broker strings comprising of hostname and port.
| Python      | `KafkaTopics`                     | `KafkaServers`
| Go          | `KafkaTopics`                     | `KafkaServers`
| Javscript   | `KafkaTopics`                     | `KafkaServers`
| Ruby        | `KafkaTopics`                     | `KafkaServers`
|=================================================================
////

=== ClowdEnv Configuration

Configuring the *Kafka Provider* is done by providing the follow JSON structure
to the ``ClowdEnv`` resource. Further details of the options available can be
found in the API reference. A minimal example is shown below for the
``operator`` mode. Different modes can use different configuration options,
more information can be found in the API reference.

[source,yaml]
----
    apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdEnvironment
    metadata:
      name: myenv
    spec:
      # Other Env Config
      providers:
        kafka:
          mode: operator
          pvc: false
----


== Cyndi

:kafka-connect: https://docs.confluent.io/platform/current/connect/index.html#kafka-connect
:project-cyndi: https://consoledot.pages.redhat.com/docs/dev/services/inventory.html#cyndi
:cyndi-operator: https://github.com/RedHatInsights/cyndi-operator#cyndi-operator
:clowder-api-cyndi: https://redhatinsights.github.io/clowder/clowder/dev/api_reference.html#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-cyndispec

{kafka-connect}[Kafka Connect] is the core component used to perform Inventory’s host database
syndication for some of the Insights platform applications, with the Cyndi operator managing the
creation of KafkaConnector resources which facilitate the synchronization process via a `CyndiPipeline`
resource.

{kafka-connect}[Kafka Connect] streams table updates to keep data syndicated between the host
inventory DB and the application database's "hosts" view.

The *cyndi* attribute of a ClowdApp definition causes Clowder to ensure that a `CyndiPipeline` is in
place for the ClowdApp. In ephemeral environments, Clowder will create the CyndiPipeline resource,
itself, while in static environments like stage/prod, the CyndiPipeline is expected to already be
present in the cluster. The ClowdEnvironment configuration controls Clowder's behavior in these
different environments.

Please refer to the corresponing projects for more information about the
{project-cyndi}[Cyndi project], the `CyndiPipeline` resource or the {cyndi-operator}[Cyndi Operator]
itself.

=== ClowdApp Configuration

In order to request a `ClowdApp` to get the host syndication enabled by Cyndi, the `cyndi` stanza
needs to be used. A snippet of how that config would look like follows:

[source,yaml]
----
# my-clowdapp.yml
# ...
cyndi:
  enabled: true
  appName: fancyapp
  insightsOnly: true
# ...
----

The attributes are described in Clowder’s API Spec documentation {clowder-api-cyndi}[here]

* *enabled* `[bool] default: true` - enables or disables the Cyndi dependency for this particular ClowdApp resource.
* *appName* `[str] default: ''` - a string that sets the unique identifier of this ClowdApp on Cyndi.
* *insightsOnly* `[bool] default: false` - enables the data syndication for all hosts or Insights hosts only.
