= Object Store Provider

The *Object Store Provider* is responsible for providing access to one or more
buckets for object storage.

== ClowdApp Configuration

To request an object store bucket, a `ClowdApp` would use the `buckets` stanza,
a partial example of which is shown below.

[source,yaml]
----
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdApp
metadata:
  name: myapp
spec:
  # Other App Config
  objectStore:
  - my-bucket-name
----

== ClowdEnv Configuration

The *Object Store Provider* will run in one of the following modes. These are
set up by the ClowdEnvironment. Depending on the environment you are running
you may or may not have access to change this mode. More information on
provider configuration is at the bottom of this page.

=== minio

In `minio` mode, the *Object Store Provider* will provision a single node Minio
instance in the namespace defined in the `ClowdEnv` for the environment.
Buckets will be created as requested by apps. Multiple apps can request the
same bucket, they will be created the first time. Buckets are not cleaned up if
all apps no longer require them.

ClowdEnv Config options available:

- `pvc`

=== app-interface

In app-interface mode, the *Object Store Provider* does not create any resources.
In order to provide te configuration to the `cdappconfig.json` it searches
through all the k8s Secrets in the same namespace as the `ClowdApp` looking
for one where the `bucket` field of the Secret matches the requested bucket
name in the ClowdApp.

== Generated App Configuration

The Object Store configuration appears in the cdappconfig.json with the
following structure. The bucket name that was requested in the `ClowdApp` will
be presented as the `requestedName` attribute in the bucket object. The *Object
Store Provider* may modify the name in some future modes where a single object
store server is shared between multiple environments. This allows the same
bucket name to be requested by apps in different environments without them
polluting each other. Apps should use the `name` attribute of a bucket when
connecting to the Object Store server.

A helper is available below to facilitate quick access via a map.

=== JSON structure

[source,json]
----
{
  "objectStore": {
    "hostname": "endpoint.env.svc",
    "port": 9292,
    "accessKey": "Testing",
    "secretKey": "Testing",
    "tls": false,
    "buckets": [
      {
        "accessKey": "accessKey1",
        "secretKey": "secretKey1",
        "requestedName": "my-bucket-name",
        "name": "my-bucket-name-663rr23"
      }
    ]
  }
}
----

=== Client access

For supported languages, the object store configuration is access via the
following attribute names.

|=======================================
| Language  | Attribute Name            
| Python    | `LoadedConfig.objectStore`
| Go        | `LoadedConfig.ObjectStore`
| Javscript | `LoadedConfig.objectStore`
| Ruby      | `LoadedConfig.objectStore`
|=======================================

=== Client helpers

`ObjectBuckets` returns a map of bucket objects, using the original requested
name as the key and the bucket object as the value.                    

[options="header"]
|===================================
| Name        | Object Store Buckets
| Python      | `ObjectBuckets`     
| Go          | `ObjectBuckets`     
| Javscript   | `ObjectBuckets`     
| Ruby        | `ObjectBuckets`     
|===================================

=== ClowdEnv Configuration

Configuring the *Object Store Provider* is done by providing the follow JSON
structure to the `ClowdEnv` resource. Further details of the options available
can be found in the API reference. A minimal example is shown below for the
`minio` mode. Different modes can use different configuration options, more
information can be found in the API reference.

[source,yaml]
----
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvivonment
metadata:
  name: myenv
spec:
  # Other Env Config
  providers:
    objectStore:
      mode: minio
      pvc: false
----
