= Web Provider

The *Web Provider* is responsible for creating the Service for the
public/private port and adding the port to the container template on the
deployment.

== ClowdApp Configuration

The public and private ports can be enabled by using the `webServices` stanza
on the `ClowdApp` specification.

[source,yaml]
----
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdApp
metadata:
  name: myapp
spec:
  # Other App Config
  deployments:
    name: inventory
    podSpec: 
      image: quay.io/psav/clowder-hello
    webServices:
      public:
        enabled: true
        apiPath: hello
        whitelistPaths:
        - /api/hello/openapi.json
      private:
        enabled: true
----

== ClowdEnv Configuration

The *Web Provider* will run in one of the following modes. These are set up by
the ClowdEnvironment. Depending on the environment you are running you may or
may not have access to change this mode. More information on provider
configuration is at the bottom of this page.

=== operator

In operator mode, the *Web Provider* will set the port and service for a
deployment.

ClowdEnv Config options available:

- `port`
- `privatePort`
- `apiPrefix`
- `BOPURL`

=== local

In local mode, the *Web Provider* will setup an entire mocked backend including
SSO, BOP and an aggregated gateway.

All pods which have the `webServices.public.enabled` set to `true` will also
have an auth pod injected into them which will be configured to work with the
SSO server and BOP URL. This will have a new port added to the service which
the gateway will be configured to use.

The `apiPath` parameter sets the URL that the service will be routed for. `/api/<apiPath>` will
be configured to route to the `auth` service port for that deployment.

The `whitelistPaths` parameter sets the paths that will not be required to go through authentication. These paths will always be able to be hit without auth. The following declarations are possible

- /absolute/path
- *prefixed/path
- /suffixed/path*
- *

ClowdEnv Config options available:

- `port`
- `privatePort`
- `apiPrefix`
- `authPort`

== Generated App Configuration

The Metrics configuration appears in the cdappconfig.json with the following
structure.

=== JSON structure

[source,json]
----
{
  "publicPort": 8000,
  "privatePort": 10000,
  "apiPrefix": "/api"
}
----

=== Client access

For supported languages, the web configuration is access via the following
attribute names.

|======================================
| Language  | Attribute Name           
| Python    | `LoadedConfig.publicPort`
| Go        | `LoadedConfig.PublicPort`
| Javscript | `LoadedConfig.publicPort`
| Ruby      | `LoadedConfig.publicPort`
|======================================

=== ClowdEnv Configuration

The *Web Provider* can be configured to set the public port, private port and
path as follows in this example.

[source,yaml]
----
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvivonment
metadata:
  name: myenv
spec:
  # Other Env Config
  providers:
    web:
      mode: operator
      privatePort: 10000
      port: 8000
----
