apiVersion: v1
kind: ConfigMap
metadata:
  name: clowder-config
data:
  clowder_config.json: |
    {
        "debugOptions": {
            "trigger": {
                "diff": ${DEBUG_TRIGGERS}
            },
            "cache": {
                "create": ${DEBUG_CACHE_CREATE},
                "update": ${DEBUG_CACHE_UPDATE},
                "apply": ${DEBUG_CACHE_APPLY}
            },
            "pprof": {
                "enable": ${DEBUG_PPROF_ENABLE}
            }
        },
        "features": {
            "createServiceMonitor": ${CREATE_SERVICE_MONITORS},
            "watchStrimziResources": ${WATCH_STRIMZI_RESOURCES},
            "enableKedaResources": ${ENABLE_KEDA_RESOURCES},
            "perProviderMetrics": ${PER_PROVIDER_METRICS},
            "reconciliationMetrics": ${RECONCILIATION_METRICS},
            "enableDependencyMetrics": ${ENABLE_DEPENDENCY_METRICS}
        },
        "settings": {
            "managedKafkaEphemDeleteRegex": "${MANAGED_EPHEM_DELETE_REGEX}"
        },
        "images": {
            "objectStoreMinio": "${OBJECTSTORE_IMAGE}",
            "featureFlagsUnleash": "${FEATUREFLAGS_IMAGE}"
        }
    }
