# Adds namespace to all resources.
namespace: clowder-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: clowder-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml

# - clowder_config.yaml


resources:
- legacy_service.yaml
- ../crd
- ../rbac
- ../manager
- ../webhook
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: manager_webhook_patch.yaml
- path: manager.yaml
- path: webhook_cert_annotation.yaml
- path: webhook_cert.yaml
- path: mutate_webhook_cert.yaml
