issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "web.Config.WebPort is deprecated"
    - linters:
        - staticcheck
      text: "broker.Sasl.SecurityProtocol is deprecated"
    - path: apis/cloud.redhat.com/v1alpha1/groupversion_info.go
      linters:
        - gofmt
        - goimports
  exclude:
    - "G108: Profiling endpoint is automatically"
linters:
  enable:
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused
    - bodyclose
