#!/usr/bin/env python3

import json
import sys
import time

if len(sys.argv) == 2:
    app_filter = sys.argv[1]
else:
    app_filter = None

for line in sys.stdin:
    js = json.loads(line)
    ts = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(js["ts"])))
    if app_filter:
        if app_filter == js["app"]:
            print(f'[{ts}] {js["msg"]}')
    else:
        app = "[%s]" % js["app"] if "app" in js else ""
        print(f'[{ts}] {app} {js["msg"]}')
