apiVersion: v1
kind: Template
metadata:
  name: clowder
parameters:
- name: IMAGE_TAG
  value: latest
- name: IMAGE
  value: quay.io/redhat-services-prod/hcm-eng-prod-tenant/clowder
- name: DEBUG_TRIGGERS
  value: "false"
- name: DEBUG_CACHE_CREATE
  value: "false"
- name: DEBUG_CACHE_UPDATE
  value: "false"
- name: DEBUG_CACHE_APPLY
  value: "false"
- name: DEBUG_PPROF_ENABLE
  value: "false"
- name: CREATE_SERVICE_MONITORS
  value: "false"
- name: WATCH_STRIMZI_RESOURCES
  value: "false"
- name: PER_PROVIDER_METRICS
  value: "false"
- name: RECONCILIATION_METRICS
  value: "false"
- name: ENABLE_DEPENDENCY_METRICS
  value: "false"
- name: MANAGED_EPHEM_DELETE_REGEX
  value: ".*ephemeral.*"
- name: ENABLE_KEDA_RESOURCES
  value: "false"
- name: DISABLE_STRIMZI_FINALIZER
  value: "false"
objects: []
