apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdApp
metadata:
  name: hello
  namespace: jumpstart
spec:
  # The name of the ClowdEnvironment providing the services
  envName: env-jumpstart

  # The bulk of your App. This is where your running apps will live
  deployments:
  - name: app
    # Creates a Service on port 8000
    webServices:
      public:
        enabled: true
    # Give details about your running pod
    podSpec:
      image: quay.io/psav/clowder-hello

  # Request kafka topics for your application here
  kafkaTopics:
    - replicas: 3
      partitions: 64
      topicName: topicone

  # Creates a database if local mode, or uses RDS in production
  database:
    # Must specify both a name and a major postgres version
    name: jumpstart-db
    version: 16
