# permissions for end users to view clowdapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clowdapp-viewer-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdapps/status
  verbs:
  - get
