# permissions for end users to view clowdjobinvocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clowdjobinvocation-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdjobinvocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdjobinvocations/status
  verbs:
  - get
