apiVersion: v1
kind: Template
metadata:
  name: clowder-olm-bundle
parameters:
- name: IMAGE_TAG
  value: latest
- name: IMAGE
  value: quay.io/cloudservices/clowder-index
- name: TARGET_NAMESPACE
  value: clowder
- name: DEBUG_TRIGGERS
  value: "false"
- name: DEBUG_CACHE_CREATE
  value: "false"
- name: DEBUG_CACHE_UPDATE
  value: "false"
- name: DEBUG_CACHE_APPLY
  value: "false"
- name: CREATE_SERVICE_MONITORS
  value: "false"
- name: WATCH_STRIMZI_RESOURCES
  value: "false"
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: clowder-source
  spec:
    sourceType: grpc
    image: ${IMAGE}:${IMAGE_TAG}
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: clowder
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: clowder
  spec:
    channel: alpha
    name: clowder
    source: clowder-source
    sourceNamespace: ${TARGET_NAMESPACE}
- apiVersion: v1
  kind: Service
  metadata:
    name: clowder-controller-manager
    labels:
      operator-name: clowder
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: metrics
    selector:
      control-plane: controller-manager
      operator-name: clowder
    type: ClusterIP
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: clowder-config
  data:
    clowder_config.json: |
      {
          "debugOptions": {
              "trigger": {
                  "diff": ${DEBUG_TRIGGERS}
              },
              "cache": {
                  "create": ${DEBUG_CACHE_CREATE},
                  "update": ${DEBUG_CACHE_UPDATE},
                  "apply": ${DEBUG_CACHE_APPLY}
              }
          },
          "features": {
              "createServiceMonitor": ${CREATE_SERVICE_MONITORS},
              "watchStrimziResources": ${WATCH_STRIMZI_RESOURCES}
          }
      }
