{
 "title": "Clowder Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ClowdApps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(clowd_app_managed_apps)" }
   ]
  },
  {
   "title": "ClowdEnvs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(clowd_env_managed_envs)" }
   ]
  },
  {
   "title": "Pod Container Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"clowder\", container=\"manager\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod Replica Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"clowder\"}"
    }
   ]
  },
  {
   "title": "WorkQueue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{service=\"clowder-controller-manager\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Managed Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(clowd_app_managed_apps)", "legendFormat": "ClowdApps" },
    { "expr": "sum(clowd_env_managed_envs)", "legendFormat": "ClowdEnvs" }
   ]
  },
  {
   "title": "Production version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(csv_succeeded{exported_namespace=\"clowder\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Stage version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(csv_succeeded{exported_namespace=\"clowder\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Fedramp version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(csv_succeeded{exported_namespace=\"clowder\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Reconciliation Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=~\"clowdenvironment|clowdapp\",result=\"error\"}[5m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliations Per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=~\"clowdenvironment|clowdapp\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}