apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clowdappreference.cloud.redhat.com
spec:
  group: cloud.redhat.com
  names:
    plural: clowdappreferences
    singular: clowdappreference
    kind: ClowdAppReference
    shortNames:
    - appref
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
