---
name: Submit docs

on:
  push:
    branches: 
    - master

jobs:
  docs_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with: 
          ref: gh_pages
      - uses: actions/setup-node@v2
      - name: Install packages and deps
        run: |
          npm install @antora/cli @antora/site-generator-default
          ./node_modules/.bin/antora playbook.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/*
          git commit -m "Updated pages for $GITHUB_SHA"
          git push
